### PR TITLE
Determine kind ( normal/build/dev) for all dependencies (not just edges)

### LINKED ISSUE #114: [depdive] Add dependency kind in the output for dep metrics
- [ ] dev/ build/ prod?

### PR DESCRIPTION
**Pull request by nasifimtiazohi**
# Changes made
1. Get kind ( normal/build/dev) for all dependencies (not just edges)
2. All normal transitives of normal deps are normal
3. Any build deps to any dep and all normal deps to build deps are build deps, if they're not already in normal list
4. All deps to dev deps are dev, if they're not already in normal or build list

# Note:
both `guppy` and `cargo-tree` filters only by edges, therefore, bot determining a final kind for each dependency by themselves. 

[`guppy::graph::PackageLink::dev_only`](https://docs.rs/guppy/0.9.0/guppy/graph/struct.PackageLink.html#method.dev_only) returns false for an edge between a normal dependency of a dev dependency to the root application. However, Isn't that edge is only counted in a dev build? Also, in that way how is the function different than [`guppy::graph::PackageLink::dev::is_present`](https://docs.rs/guppy/0.9.0/guppy/graph/struct.PackageLink.html#method.dev) ?

closes #114

### CODE REVIEW

**Review by bmwill — DISMISSED** [review]

**Comment by nasifimtiazohi** [comment]
@bmwill moved octocrab to build-deps in test crate in the prior PR which cargo-geiger doesn't scan. Therefore, needed to adjust some testing. There are three new commits inclduing fixups pushed after what was approved.

**Review by bmwill — APPROVED** [review]

**Pull request closed without merging**
